language: java

jdk:
  - oraclejdk7

env:
  matrix:
    - AS=wildfly-8.x
    - AS=jboss-7.1.x
    - AS=jboss-6.1.x
    - AS=jboss-5.1.x
    - AS=jboss-4.2.x
    - AS=glassfish-4.x
    - AS=glassfish-3.x
    - AS=jetty-9.x
    - AS=jetty-8.x
    - AS=jetty-7.x
    - AS=tomcat-8.x
    - AS=tomcat-7.x
    - AS=tomcat-6.x
    #- AS=weblogic-12.x
    - AS=resin-4.x
    - AS=jonas-5.x
    - AS=geronimo-3.x

script: "mvn clean test -P ${AS}"
